branch-defaults:
  development:
    environment: ums-beanstalk-elb
  eb-version:
    environment: ums-beanstalk-elb
environment-defaults:
  Sample-env:
    branch: null
    repository: null
global:
  application_name: ums-single-instance
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Passenger with Ruby
    2.3 running on 64bit Amazon Linux/2.3.2
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
